--- #YAML:1.0
name: HTML-TagCloud
version: 0.34
author:
  - Leon Brocard, C<< <acme@astray.com> >>.
abstract: Generate An HTML Tag Cloud
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
