---
name: HTML-TagCloud
version: 0.31
author:
  - 'Leon Brocard, C<< <acme@astray.com> >>.'
abstract: Generate An HTML Tag Cloud
license: perl
requires:
  Test::More: 0
provides:
  HTML::TagCloud:
    file: lib/HTML/TagCloud.pm
    version: 0.31
generated_by: Module::Build version 0.2611
