---
abstract: 'Generate An HTML Tag Cloud'
author:
  - 'Leon Brocard, C<< <acme@astray.com> >>.'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-TagCloud
provides:
  HTML::TagCloud:
    file: lib/HTML/TagCloud.pm
    version: 0.37
requires:
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.37
